#!/usr/bin/env bash
# changes localhost to resolve to 127.0.0.2
# and facebook.com to resolve to 8.8.8.8
cp /etc/hosts ~/hosts
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts
sed -i 's/.*facebook.com//g' ~/hosts
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts
cp -f ~/hosts /etc/hosts
